### ISSUE TITLE
No alive nodes found in your cluster for AWS

### ISSUE THREAD

**Issue by nal-ws-001** [mailerlite/laravel-elasticsearch#108]
I got No alive nodes found in your cluster for AWS.
Library Version - cviebrock/laravel-elasticsearch:^2
PHP - >=7.1.3
Laravel - 5.8.*

**Comment by cviebrock** [comment]
Are you using ES 5?  If not, then I'd try the latest version of this package instead of `^2`.

Unfortunately, I don't have a AWS cluster to test this on.  But I can say that the package is really just a wrapper for the official PHP ES client ... so maybe try configuring that manually and seeing if you have the same issue?

Also, post your config here for others to see.  Maybe they have some ideas.

**Comment by nal-ws-001** [comment]
Fixed by upgrading version
