### ISSUE TITLE
 No alive nodes found in your cluster

### ISSUE THREAD

**Issue by tripleten** [mailerlite/laravel-elasticsearch#112]
I am using Laravel 8 and Elasticsearch version 7.10.0, my environment details are below:

"php": "^7.3|^8.0",
 "cviebrock/laravel-elasticsearch": "^8.0",
 "elasticsearch/elasticsearch": "^7.10",
"fideloper/proxy": "^4.4",
"fruitcake/laravel-cors": "^2.0",
"guzzlehttp/guzzle": "^7.0.1",
"laravel/framework": "^8.12",
"laravel/tinker": "^2.5",
"laravel/ui": "^3.1",
"league/csv": "^9.6",
"spatie/laravel-permission": "^3.17",
"yajra/laravel-datatables-oracle": "^9.14"

Also, the elasticsearch host and other details as in the .env file are below:

ELASTICSEARCH_HOST="https://7e93d3d57e624dfeb051a57cb113171c.ap-south-1.aws.elastic-cloud.com"
ELASTICSEARCH_PORT=9243
ELASTICSEARCH_SCHEME=https
ELASTICSEARCH_USER=******
ELASTICSEARCH_PASS=**********

Could you please suggest what could be the possible reason for this not working from my localhost ( XAMPP running on Windows 10 )?

**Comment by cviebrock** [comment]
This package is simply a wrapper around the official `elasticsearch/elasticsearch` client to make configuration more Laravel-y.  If you are getting errors about no nodes, or other ES issues, then I suspect the issue is with your credentials or you ES setup in general.  I'd suggest trying to configure the official client directly using the same credentials and see if that gives you the same error.

Also, it looks like you are using AWS?   If so, read over the documentation here: https://github.com/cviebrock/laravel-elasticsearch#connecting-to-aws-elasticsearch-service
