### ISSUE TITLE
Whoops! There was an error.

### ISSUE THREAD

**Issue by dvlpr91** [mailerlite/laravel-elasticsearch#46]
I see the message that "No alive nodes found in your cluster".

Please tell me about step-by-step installation and setup. (T_T)

Somebody help me! I'm a Elasticsearch starter.

========================
my ".env" file.

```
ELASTICSEARCH_HOST=mydomain.test
ELASTICSEARCH_PORT=9200
ELASTICSEARCH_SCHEME=http
ELASTICSEARCH_USER=
ELASTICSEARCH_PASS=
```
========================
my "router.php" file.

```
Route::get('/user/id/1', function () { 
  $data = [ 
    'body' => [ 
      'testField' => 'abc'
    ],
    'index' => 'my_index',
    'type' => 'my_type',
    'id' => 'my_id',
  ];

  Elasticsearch::index($data);
});
```

---------------------------------
in homestead 7.9 of laravel 5.6

**Comment by petercoles** [comment]
That you're getting this message confirms that you have have set up and configured this package correctly.

Your problem is with your Elasticsearch cluster, which is beyond the scope of this package. However there's [a helpful, though rather old github gist ](https://gist.github.com/lukaswhite/c50a6cf82ce0b7aa6b2a) describing the steps you need to go through to get a working cluster in Homestead.

**Comment by cviebrock** [comment]
As @petercoles said, the issue you have is not with the package, but with getting ES up and running in your environment.  Hopefully that gist helps you out.  If not, maybe ask on the laracasts.com forums?
