### ISSUE TITLE
integrating with logstash

### ISSUE THREAD

**Issue by farshadff** [mailerlite/laravel-elasticsearch#70]
i want to know if i can integrate my laravel logs in logstash with this package or not because it says nothing about logstash

**Comment by cviebrock** [comment]
You could use this package: https://github.com/nulpunkt/monolog-elasticsearch-logstashformat

If you do (and you use my package as well), then instead of initializing the ES client like they suggest:

```php
$client = new Elasticsearch\Client(['hosts' => ['http://example.com:9200']]);
```

I think you could just do this:

```php
$client = app(Elasticsearch\Client::class);
```

Or if you have a specific connection for logging, and use facades:

```php
$client = Elasticsearch::connection('connectionName');
```
